language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm-nightly

install: composer update --dev --no-interaction

script: phpunit --verbose

sudo: false
